<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-05-04T07:32:28 IST" name="Surefire suite" finished-at="2024-05-04T07:32:32 IST" duration-ms="4008">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunnerTestNG.TestRunnerTestNG@35047d03]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2024-05-04T07:32:28 IST" name="Surefire test" finished-at="2024-05-04T07:32:32 IST" duration-ms="4008">
      <class name="testRunnerTestNG.TestRunnerTestNG">
        <test-method is-config="true" signature="setUpClass(org.testng.ITestContext)[pri:0, instance:testRunnerTestNG.TestRunnerTestNG@35047d03]" started-at="2024-05-04T07:32:29 IST" name="setUpClass" finished-at="2024-05-04T07:32:29 IST" duration-ms="526" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@1aabf50d]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRunnerTestNG.TestRunnerTestNG@35047d03]" started-at="2024-05-04T07:32:29 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-05-04T07:32:32 IST" duration-ms="3417" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify user is seeing validation message when user name is valid and password is invalid"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["This feature is to test the negative test cases"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email or password]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or password]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testingacademy.stepDefinitionsFiles.APurchaseOrder.i_should_see_validation_message(APurchaseOrder.java:67)
at âœ½.I should see "Incorrect email or password" message(file:///C:/Users/mural/eclipse-workspace/CucumberDemo/src/test/java/featureFiles/ValidationErrors.feature:11)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:testRunnerTestNG.TestRunnerTestNG@35047d03]" started-at="2024-05-04T07:32:32 IST" name="tearDownClass" finished-at="2024-05-04T07:32:32 IST" duration-ms="16" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- testRunnerTestNG.TestRunnerTestNG -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
